name: CI

on:
  push:
    branches: [ main, develop, feature/**, chore/** ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    name: Build and Test (macOS)
    runs-on: macos-latest

    steps:
      # --- Checkout source ---
      - name: Checkout repository
        uses: actions/checkout@v4

      # --- Cache Homebrew bottle downloads ---
      - name: Cache Homebrew bottles
        uses: actions/cache@v4
        with:
          path: ~/Library/Caches/Homebrew/downloads
          key: macos-brew-bottles-${{ runner.os }}-v1
          restore-keys: macos-brew-bottles-

      # --- Install dependencies (no auto update) ---
      - name: Install dependencies
        env:
          HOMEBREW_NO_AUTO_UPDATE: 1
        run: |
          brew install --force-bottle llvm opencv
          echo "/opt/homebrew/opt/llvm/bin" >> $GITHUB_PATH
          brew link --overwrite opencv

      # --- Verify toolchain availability ---
      - name: Verify compiler and coverage tools
        run: |
          clang++ --version
          llvm-cov --version
          llvm-profdata --version
          clang-tidy --version

      # --- Configure project (CMake preset: test) ---
      - name: Configure CMake
        run: cmake --preset test

      # --- Build tests (with coverage flags) ---
      - name: Build SensorTests
        run: cmake --build --preset test --target SensorTests -j$(sysctl -n hw.logicalcpu)

      # --- Run tests with Catch2 ---
      - name: Run unit tests
        working-directory: build/test
        run: ctest --output-on-failure -V

      # --- Generate HTML coverage summary ---
      - name: Generate coverage report
        working-directory: build/test
        run: |
          echo "==> Merging raw profiles"
          llvm-profdata merge -sparse coverage_*.profraw -o coverage.profdata || true
          echo "==> Generating HTML coverage summary"
          llvm-cov show ./SensorTests \
            -instr-profile=coverage.profdata \
            -format=html -output-dir=coverage-report \
            -ignore-filename-regex='external/*' \
            -Xdemangler=llvm-cxxfilt || true

      # --- Upload coverage summary as artifact ---
      - name: Upload HTML coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: build/test/coverage-report
